name: "my-job-stage"

on: 
  push: 
    branches:
      - stage

jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - name: Say hello
        run: echo "Hola Mundo stage test" 
  second-job:
    if: ${{ github.ref == 'refs/heads/main' }}
    needs: my-job
    runs-on: ubuntu-latest
    steps:
      - name: Say hello
        run: echo "Hola Mundo" 
